---
- name: Set up Web Server (Ubuntu)
  hosts: webservers
  become: yes
  tasks:
    - name: Update APT package cache
      apt:
        update_cache: yes

    - name: Install Apache and PHP
      apt:
        name: 
          - apache2
          - php
          - libapache2-mod-php
        state: present

    - name: Start and enable Apache
      service:
        name: apache2
        state: started
        enabled: true

    - name: Remove old website files
      file:
        path: /var/www/html/*
        state: absent

    - name: Upload PHP website
      copy:
        src: /etc/ansible/ansible_playbook/website/
        dest: /var/www/html/
        owner: www-data
        group: www-data
        mode: '0755'

- name: Set up Database Server (Arch)
  hosts: dbservers
  become: yes
  tasks:
    - name: Update package manager (Pacman)
      pacman:
        update_cache: yes

    - name: Install MariaDB
      pacman:
        name: mariadb
        state: present

    - name: Initialize MariaDB database
      command: mysql_install_db --user=mysql --basedir=/usr --datadir=/var/lib/mysql
      args:
        creates: /var/lib/mysql/mysql

    - name: Start and enable MariaDB service
      service:
        name: mariadb
        state: started
        enabled: true
